# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#   yadt-config-rpm-maker
#   Copyright (C) 2011-2013 Immobilien Scout GmbH
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

Vagrant::Config.run do |config|
  config.vm.box = "yadt-config-rpm-maker-ScientificEL6.5"
  config.vm.box_url = "https://atlas.hashicorp.com/bytepark/boxes/scientific-6.5-64/versions/0.1.0/providers/virtualbox.box"

  Vagrant::Config.run do |config|
    config.vm.provision :shell, :inline => "cd /vagrant; sudo -u vagrant bash provision.sh"
  end
end
